AWSTemplateFormatVersion: 2010-09-09
Description: Validates fulfilment information for a given subscription name
Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
    Default: CODE
  FileLocation:
    Description: Location of uploaded fulfilment files
    Type: String
    AllowedValues:
      - fulfilment-export-code/uploaded
      - fulfilment-export-prod/uploaded
  ApiName:
    Type: String
    AllowedValues:
    - fulfilment-lookup-api-CODE
    - fulfilment-lookup-api-PROD
    Default: fulfilment-lookup-api-CODE

Conditions:
  CreateProdMonitoring: !Equals [ !Ref Stage, PROD ]

Resources:
  FulfilmentExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: FulfilmentLambdaPolicy
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - lambda:InvokeFunction
              Resource: "*"
        - PolicyName: ReadPrivateCredentials
          PolicyDocument:
            Statement:
              Effect: Allow
              Action: s3:GetObject
              Resource: !Sub arn:aws:s3:::gu-reader-revenue-private/membership/fulfilment-lookup/${Stage}/*
        - PolicyName: ReadFulfilmentBucket
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
              Resource: !Sub arn:aws:s3:::${FileLocation}/*

  FulfilmentLookupLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub fulfilment-lookup-${Stage}
      Code:
        S3Bucket: fulfilment-lookup-dist
        S3Key: !Sub membership/${Stage}/fulfilment-lookup/fulfilment-lookup.jar
      Environment:
        Variables:
          Stage: !Ref Stage
      Description: Validates fulfilment information for a given subscription name
      Handler: com.gu.fulfilmentLookup.Lambda::handler
      MemorySize: 1536
      Role:
          Fn::GetAtt:
          - FulfilmentExecutionRole
          - Arn
      Runtime: java8.al2
      Timeout: 60
    DependsOn:
    - FulfilmentExecutionRole

  FulfilmentLookupApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Sub fulfilment-lookup-${Stage}
      Principal: apigateway.amazonaws.com
    DependsOn:
    - FulfilmentLookupLambda

  FulfilmentLookupApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Description: Endpoint used to lookup subscription for given fulfilment file
      Name: !Sub ${ApiName}

  FulfilmentLookupApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Description: Key required to call fulfilment lookup API
      Enabled: true
      Name: !Sub fulfilment-lookup-api-key-${Stage}
      StageKeys:
        - RestApiId: !Ref FulfilmentLookupApi
          StageName: !Sub ${Stage}
    DependsOn:
    - FulfilmentLookupApi
    - FulfilmentLookupApiStage

  FulfilmentLookupUsagePlan:
    Type: "AWS::ApiGateway::UsagePlan"
    Properties:
      UsagePlanName: !Sub ${ApiName}
      ApiStages:
      - ApiId: !Ref FulfilmentLookupApi
        Stage: !Ref FulfilmentLookupApiStage
    DependsOn:
    - FulfilmentLookupApi
    - FulfilmentLookupApiStage

  FulfilmentLookupUsagePlanKey:
    Type: "AWS::ApiGateway::UsagePlanKey"
    Properties:
      KeyId: !Ref FulfilmentLookupApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref FulfilmentLookupUsagePlan
    DependsOn:
    - FulfilmentLookupApiKey
    - FulfilmentLookupUsagePlan

  FulfilmentLookupProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref FulfilmentLookupApi
      ParentId: !GetAtt [FulfilmentLookupApi, RootResourceId]
      PathPart: fulfilment-lookup
    DependsOn:
    - FulfilmentLookupApi

  FulfilmentLookupMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      ApiKeyRequired: true
      RestApiId: !Ref FulfilmentLookupApi
      ResourceId: !Ref FulfilmentLookupProxyResource
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FulfilmentLookupLambda.Arn}/invocations
    DependsOn:
      - FulfilmentLookupApi
      - FulfilmentLookupLambda
      - FulfilmentLookupProxyResource

  FulfilmentLookupApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      Description: Stage for fulfilment-lookup-api
      RestApiId: !Ref FulfilmentLookupApi
      DeploymentId: !Ref FulfilmentLookupApiDeployment
      StageName: !Sub ${Stage}
    DependsOn:
    - FulfilmentLookupApi

  FulfilmentLookupApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Deploys fulfilment-lookup-api into an environment/stage
      RestApiId: !Ref FulfilmentLookupApi
    DependsOn:
    - FulfilmentLookupMethod

  FulfilmentLookup5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: CreateProdMonitoring
    Properties:
      AlarmActions:
      - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:fulfilment-dev
      AlarmName: 5XX rate from fulfilment-lookup-api
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub ${ApiName}
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: 7200
      Statistic: Sum
      Threshold: 2

  FulfilmentLookup4xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: CreateProdMonitoring
    Properties:
      AlarmActions:
      - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:fulfilment-dev
      AlarmName: 4XX rate from fulfilment-lookup-api
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub ${ApiName}
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Period: 7200
      Statistic: Sum
      Threshold: 2
